class Solution:
    def numIdenticalPairs(self, nums: List[int]) -> int:
        """
        Thought:
        - Goal:
            Find the total number of good pairs (i, j) in the array such that nums[i] == nums[j] and i < j.
        - Idea:
            If a number appears N times in the array, it can form C(N, 2) = N * (N - 1) / 2 good pairs.
            We can count the frequency of each number first, then sum up the pairs generated by each unique number.
        - Steps:
            1. Count the occurrences of each number using a hash map or Counter.
            2. Iterate through the frequency counts.
            3. Calculate N * (N - 1) // 2 for each count and add it to the total.
            4. Return the total number of good pairs.
        - Time Complexity:
            O(N), where N is the length of the array `nums`. Counting frequencies takes O(N), and iterating over unique elements takes at most O(N).
        - Space Complexity:
            O(N), as the hash map will store at most N unique elements in the worst case.
        """
        total = 0
        counts = Counter(nums)

        for count in counts.values():
            total += count * (count - 1) // 2

        return total
